# Generated by Django 3.2.3 on 2021-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('query', models.TextField(max_length=150, verbose_name='desc')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
            ],
        ),
    ]
